"""adds relationships to Stage

Revision ID: 21d045b3209b
Revises: 7cede7b410db
Create Date: 2024-04-09 12:33:09.634704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d045b3209b'
down_revision = '7cede7b410db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_game_stage_id_stage'), 'stage', ['stage_id'], ['id'])

    with op.batch_alter_table('stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tournament_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_stage_tournament_id_tournament'), 'tournament', ['tournament_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stage_tournament_id_tournament'), type_='foreignkey')
        batch_op.drop_column('tournament_id')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_stage_id_stage'), type_='foreignkey')
        batch_op.drop_column('stage_id')

    # ### end Alembic commands ###
