"""adds tournament_teams join table

Revision ID: 6099c1ceaea9
Revises: 21d045b3209b
Create Date: 2024-04-10 12:42:19.601596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6099c1ceaea9'
down_revision = '21d045b3209b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_teams',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('fk_tournament_teams_team_id_team')),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], name=op.f('fk_tournament_teams_tournament_id_tournament')),
    sa.PrimaryKeyConstraint('tournament_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_teams')
    # ### end Alembic commands ###
