"""adds basic models

Revision ID: 89486277ae75
Revises: 1c31a4015904
Create Date: 2024-04-09 11:52:06.964362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89486277ae75'
down_revision = '1c31a4015904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('own_score', sa.Integer(), nullable=True),
    sa.Column('opponent_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('minutes_per_game', sa.Integer(), nullable=True),
    sa.Column('minutes_per_break', sa.Integer(), nullable=True),
    sa.Column('is_bracket', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('num_fields', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament')
    op.drop_table('team')
    op.drop_table('stage')
    op.drop_table('game_score')
    op.drop_table('game')
    # ### end Alembic commands ###
