"""adds image to team and tournament models

Revision ID: ca46fe7f338a
Revises: 6099c1ceaea9
Create Date: 2024-04-11 13:05:16.465628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca46fe7f338a'
down_revision = '6099c1ceaea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
